In [3]:
from simworld.config import Config
from communicator.nav_communicator import nav_communicator
from manager.task_manager import TaskManager
from communicator.nav_unrealcv import NavUnrealCV


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\anaconda\envs\delivery\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\anaconda\envs\delivery\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\anaconda\envs\delivery\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\anaconda\envs\delivery\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\anaconda\envs\delivery\lib\sit

In [4]:
import os
os.environ['OPENAI_API_KEY']="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"

In [5]:
config = Config(r'C:\SimLLM-Nav\nav\configs\navllm_config.yaml')
communicator = nav_communicator(NavUnrealCV())
# traffic_controller = TrafficController(config)
# traffic_controller.init_communicator(communicator)
# task_manager = TaskManager(config, communicator, traffic_controller)
task_manager = TaskManager(config, communicator)

INFO:__init__:230:Got connection confirm: b'connected to gym_citynav'


=>Info: using ip-port socket


In [6]:
task_manager.create_world()

In [7]:
task_manager.load_agent()

In [8]:
task_manager.run_task()

Agent 0 is running
Agent 0 is navigating to destination Vector(x=-0.0, y=10000.0), current position: Vector(x=-0.0, y=0.0)
[Vector(x=-0.0, y=0.0)]
True
An error occurred: Expecting value: line 1 column 1 (char 0)
Waiting for all agents to finish...
<class 'PIL.Image.Image'>
Rgb image and depth image has been loaded
Read png can not parse response [[[ 34  33  29]
  [ 37  50  59]
  [ 35  58  68]
  ...
  [ 34  30  30]
  [ 34  31  30]
  [ 35  31  31]]

 [[133 114 111]
  [123 112 114]
  [ 40  60  69]
  ...
  [ 34  30  30]
  [ 35  31  31]
  [ 35  31  31]]

 [[200 167 164]
  [176 150 150]
  [ 45  62  70]
  ...
  [ 34  31  31]
  [ 34  31  31]
  [ 36  32  32]]

 ...

 [[187 183 111]
  [187 183 112]
  [185 180 108]
  ...
  [ 12   9   9]
  [  3   1   1]
  [  3   2   1]]

 [[185 180 106]
  [185 180 104]
  [185 180 105]
  ...
  [  7   4   4]
  [  5   3   2]
  [  4   2   1]]

 [[185 180 103]
  [183 177  97]
  [184 178  98]
  ...
  [ 25  19  17]
  [ 28  22  20]
  [ 26  20  19]]]
Error in agent 0: ufu